name = "GameInference"
uuid = "310d0266-9b5d-5b02-9507-d3a640887650"
authors = "lassepe <lasse.peters@tuhh.de>"
veresion = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NamedTupleTools = "d9ec5142-1e00-5aa0-9d6a-321866360f50"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
ParticleFilters = "c8b314e2-9260-5cf8-ae76-3be7461ca6d0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
iLQGames = "ae812560-bd7e-11e9-3bd3-b502f7cff3d3"

[compat]
julia = "1.3"
BenchmarkTools = "0.5"
CSV = "0.6"
Clustering = "0.13"
ColorSchemes = "3.9"
DataFrames = "0.21"
DataFramesMeta = "0.5"
DiffResults = "1"
Distances = "0.9"
Distributions = "0.23"
DocStringExtensions = "0.8"
ForwardDiff = "0.10"
GR = "0.49"
LaTeXStrings = "1.1"
Latexify = "0.13"
NamedTupleTools = "0.13"
POMDPModelTools = "0.2"
POMDPs = "0.8"
Parameters = "0.12"
ParticleFilters = "0.4"
Plots = "1"
ProgressMeter = "1"
RDatasets = "0.6"
Setfield = "0.6"
StaticArrays = "0.12"
StatsPlots = "0.14"
iLQGames = "0.2"
